[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ErrorAI"
version = "0.2.0"
description = "An interactive, AI-powered terminal debugging and auto-fixing library for Python."
readme = "README.md"
authors = [
    { name = "Aswanth R" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Debugging",
]
requires-python = ">=3.7"
dependencies = []

[tool.setuptools.package-data]
errorai = ["models/*.json"]

[project.urls]
Homepage = "https://github.com/yourusername/ErrorAI"
